image: 'ruby:alpine'

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - bundle install
    - gem build eisiges-di-provider-default.gemspec
  artifacts:
    paths:
      - eisiges-di-provider-default-*.gem
    expire_in: 1 week

test:
  stage: test
  script:
    - bundle install
    - bundle exec rake test

deploy:
  stage: deploy
  script:
    - gem sources -a http://gems.mccollum.enterprises/
    - gem install geminabox
    - gem inabox --host 'http://gems.mccollum.enterprises' --overwrite eisiges-di-provider-default-*.gem
  only:
    - master

after_script:
  - echo "End CI"
